#!/usr/bin/env python3
"""Pull Alpaca assets and write readme.md, tickers.kdl, and tickers.csv together.

Uses GET /v2/assets (see https://docs.alpaca.markets/reference/get-v2-assets-1).
All three outputs are regenerated from the same fetched symbol list on every successful run.

Environment (first match wins for each):
  Key: APCA_API_KEY_ID, ALPACA_API_KEY_ID, ALPACA_API_KEY
  Secret: APCA_API_SECRET_KEY, ALPACA_API_SECRET_KEY, ALPACA_SECRET_KEY
  Base URL (optional): ALPACA_API_URL, ALPACA_API_BASE_URL, APCA_API_BASE_URL,
    ALPACA_BASE_URL — default https://api.alpaca.markets (paper: https://paper-api.alpaca.markets)

Example:
  ALPACA_API_KEY=... ALPACA_SECRET_KEY=... ALPACA_API_URL=https://paper-api.alpaca.markets \\
    python3 fetch_alpaca_tickers.py

Outputs (same symbol set, sorted, written only after a successful API response):
  readme.md — JSON array (pretty, 8 symbols per line)
  tickers.kdl — KDL document with tickers { symbol "..." ... }
  tickers.csv — header symbol, one row per ticker

Each successful run appends one line to alpaca_tickers_fetch.log (next to this script).
"""

from __future__ import annotations

import csv
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone


def _append_fetch_log(log_path: str, line: str) -> None:
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(line)
        if not line.endswith("\n"):
            f.write("\n")


def _log_fail(log_path: str, base: str, *, kind: str, detail: str) -> None:
    ts = datetime.now(timezone.utc).isoformat()
    safe = detail.replace("\t", " ").replace("\n", " ")[:500]
    _append_fetch_log(log_path, f"{ts}\tFAIL\terror={kind}\tapi={base}\tdetail={safe}\n")


def _kdl_string_literal(s: str) -> str:
    return (
        '"'
        + s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        + '"'
    )


def _write_kdl(path: str, symbols: list[str]) -> None:
    lines = [
        "// Alpaca active US equity symbols (sorted). Generated by fetch_alpaca_tickers.py.",
        "tickers {",
    ]
    for sym in symbols:
        lines.append(f"    symbol {_kdl_string_literal(sym)}")
    lines.append("}")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _write_csv(path: str, symbols: list[str]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["symbol"])
        for sym in symbols:
            w.writerow([sym])


def main() -> int:
    key = (
        os.environ.get("APCA_API_KEY_ID")
        or os.environ.get("ALPACA_API_KEY_ID")
        or os.environ.get("ALPACA_API_KEY")
    )
    secret = (
        os.environ.get("APCA_API_SECRET_KEY")
        or os.environ.get("ALPACA_API_SECRET_KEY")
        or os.environ.get("ALPACA_SECRET_KEY")
    )
    base = (
        os.environ.get("ALPACA_API_URL")
        or os.environ.get("ALPACA_API_BASE_URL")
        or os.environ.get("APCA_API_BASE_URL")
        or os.environ.get("ALPACA_BASE_URL")
        or "https://api.alpaca.markets"
    ).rstrip("/")

    script_dir = os.path.dirname(os.path.abspath(__file__))
    log_path = os.path.join(script_dir, "alpaca_tickers_fetch.log")

    if not key or not secret:
        print(
            "Missing Alpaca credentials: set APCA_API_KEY_ID + APCA_API_SECRET_KEY, "
            "or ALPACA_API_KEY_ID + ALPACA_API_SECRET_KEY, "
            "or ALPACA_API_KEY + ALPACA_SECRET_KEY.",
            file=sys.stderr,
        )
        return 1

    params = urllib.parse.urlencode(
        {
            "status": "active",
            "asset_class": "us_equity",
        }
    )
    url = f"{base}/v2/assets?{params}"

    req = urllib.request.Request(
        url,
        headers={
            "APCA-API-KEY-ID": key,
            "APCA-API-SECRET-KEY": secret,
            "Accept": "application/json",
        },
        method="GET",
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            raw = resp.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"HTTP {e.code}: {body}", file=sys.stderr)
        _log_fail(log_path, base, kind="http", detail=f"status={e.code} body={body[:400]}")
        return 1
    except urllib.error.URLError as e:
        print(f"Request failed: {e}", file=sys.stderr)
        reason = e.reason if getattr(e, "reason", None) is not None else e
        _log_fail(log_path, base, kind="url", detail=str(reason))
        return 1
    except OSError as e:
        print(f"Network error: {e}", file=sys.stderr)
        _log_fail(log_path, base, kind="os", detail=str(e))
        return 1

    try:
        assets = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"Invalid JSON from API: {e}", file=sys.stderr)
        _log_fail(log_path, base, kind="json_decode", detail=str(e))
        return 1

    if not isinstance(assets, list):
        print("Expected a JSON array of asset objects.", file=sys.stderr)
        _log_fail(
            log_path,
            base,
            kind="json_shape",
            detail=f"got {type(assets).__name__}",
        )
        return 1

    tradable_only = "--all-active" not in sys.argv
    symbols: list[str] = []
    for a in assets:
        if not isinstance(a, dict):
            continue
        sym = a.get("symbol")
        if not sym:
            continue
        if tradable_only and not a.get("tradable"):
            continue
        symbols.append(sym)

    symbols = sorted(set(symbols))

    # Pretty multi-column lines similar to existing readme.md (8 symbols per line).
    per_chunk = 8
    indent = "    "
    lines: list[str] = ["["]
    for i in range(0, len(symbols), per_chunk):
        chunk = symbols[i : i + per_chunk]
        inner = ", ".join(json.dumps(s) for s in chunk)
        comma = "," if i + per_chunk < len(symbols) else ""
        lines.append(f"{indent}{inner}{comma}")
    lines.append("]")
    readme_out = "\n".join(lines) + "\n"

    readme_path = os.path.join(script_dir, "readme.md")
    kdl_path = os.path.join(script_dir, "tickers.kdl")
    csv_path = os.path.join(script_dir, "tickers.csv")

    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme_out)
    _write_kdl(kdl_path, symbols)
    _write_csv(csv_path, symbols)

    ts = datetime.now(timezone.utc).isoformat()
    filt = "tradable" if tradable_only else "all_active"
    outs = "readme.md,tickers.kdl,tickers.csv"
    _append_fetch_log(
        log_path,
        f"{ts}\tOK\tsymbols={len(symbols)}\tout={outs}\tapi={base}\tfilter={filt}\n",
    )

    print(f"Wrote {len(symbols)} symbols (from Alpaca) to:")
    print(f"  {readme_path}")
    print(f"  {kdl_path}")
    print(f"  {csv_path}")
    print(f"Logged update at {ts} (UTC) -> {log_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
