#!/usr/bin/env -S deno run --allow-net --allow-env --allow-read --allow-write
/** Pull Alpaca assets and write readme.md, tickers.kdl, and tickers.csv together.
 *
 * Uses GET /v2/assets (see https://docs.alpaca.markets/reference/get-v2-assets-1).
 * All three outputs are regenerated from the same fetched symbol list on every successful run.
 *
 * Environment (first match wins for each):
 *   Key: APCA_API_KEY_ID, ALPACA_API_KEY_ID, ALPACA_API_KEY
 *   Secret: APCA_API_SECRET_KEY, ALPACA_API_SECRET_KEY, ALPACA_SECRET_KEY
 *   Base URL (optional): ALPACA_API_URL, ALPACA_API_BASE_URL, APCA_API_BASE_URL,
 *     ALPACA_BASE_URL — default https://api.alpaca.markets (paper: https://paper-api.alpaca.markets)
 *
 * Example:
 *   deno task fetch
 *
 * Outputs (same symbol set, sorted, written only after a successful API response):
 *   readme.md — JSON array (pretty, 8 symbols per line)
 *   tickers.kdl — KDL document with tickers { symbol "..." ... }
 *   tickers.csv — header symbol, one row per ticker
 *
 * Each successful run appends one line to alpaca_tickers_fetch.log (next to this script).
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const GENERATOR = "fetch_alpaca_tickers.ts";

function envFirst(...names: string[]): string | undefined {
  for (const name of names) {
    const value = Deno.env.get(name);
    if (value) return value;
  }
  return undefined;
}

function kdlStringLiteral(s: string): string {
  return `"${s
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\n", "\\n")
    .replaceAll("\r", "\\r")}"`;
}

async function appendFetchLog(logPath: string, line: string): Promise<void> {
  await Deno.writeTextFile(logPath, line.endsWith("\n") ? line : `${line}\n`, {
    append: true,
  });
}

async function logFail(
  logPath: string,
  base: string,
  kind: string,
  detail: string,
): Promise<void> {
  const ts = new Date().toISOString();
  const safe = detail.replaceAll("\t", " ").replaceAll("\n", " ").slice(0, 500);
  await appendFetchLog(
    logPath,
    `${ts}\tFAIL\terror=${kind}\tapi=${base}\tdetail=${safe}\n`,
  );
}

function writeKdl(symbols: string[]): string {
  const lines = [
    `// Alpaca active US equity symbols (sorted). Generated by ${GENERATOR}.`,
    "tickers {",
    ...symbols.map((sym) => `    symbol ${kdlStringLiteral(sym)}`),
    "}",
    "",
  ];
  return lines.join("\n");
}

function writeCsv(symbols: string[]): string {
  const rows = [
    "symbol",
    ...symbols.map((sym) => {
      if (sym.includes(",") || sym.includes('"') || sym.includes("\n")) {
        return `"${sym.replaceAll('"', '""')}"`;
      }
      return sym;
    }),
  ];
  return `${rows.join("\n")}\n`;
}

function writeReadme(symbols: string[]): string {
  const perChunk = 8;
  const indent = "    ";
  const lines = ["["];
  for (let i = 0; i < symbols.length; i += perChunk) {
    const chunk = symbols.slice(i, i + perChunk);
    const inner = chunk.map((s) => JSON.stringify(s)).join(", ");
    const comma = i + perChunk < symbols.length ? "," : "";
    lines.push(`${indent}${inner}${comma}`);
  }
  lines.push("]");
  return `${lines.join("\n")}\n`;
}

function symbolsFromKdl(text: string): string[] {
  const symbols: string[] = [];
  const re = /^\s*symbol\s+"((?:\\.|[^"\\])*)"/gm;
  for (const match of text.matchAll(re)) {
    symbols.push(
      match[1]
        .replaceAll("\\n", "\n")
        .replaceAll("\\r", "\r")
        .replaceAll('\\"', '"')
        .replaceAll("\\\\", "\\"),
    );
  }
  return symbols;
}

function symbolsFromCsv(text: string): string[] {
  const lines = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").trimEnd().split("\n");
  if (lines.length === 0 || lines[0] !== "symbol") {
    throw new Error("tickers.csv missing header row");
  }
  return lines.slice(1).map((line) => {
    if (line.startsWith('"') && line.endsWith('"')) {
      return line.slice(1, -1).replaceAll('""', '"');
    }
    return line;
  });
}

function symbolsFromReadme(text: string): string[] {
  const parsed: unknown = JSON.parse(text);
  if (!Array.isArray(parsed) || !parsed.every((s) => typeof s === "string")) {
    throw new Error("readme.md is not a JSON string array");
  }
  return parsed;
}

function assertSameSymbols(
  label: string,
  expected: string[],
  actual: string[],
): void {
  if (expected.length !== actual.length) {
    throw new Error(
      `${label}: expected ${expected.length} symbols, got ${actual.length}`,
    );
  }
  for (let i = 0; i < expected.length; i++) {
    if (expected[i] !== actual[i]) {
      throw new Error(
        `${label}: mismatch at index ${i}: ${expected[i]!} != ${actual[i]!}`,
      );
    }
  }
}

async function writeFileAtomic(path: string, content: string): Promise<void> {
  const tmp = `${path}.${crypto.randomUUID()}.tmp`;
  await Deno.writeTextFile(tmp, content);
  await Deno.rename(tmp, path);
}

async function verifyOutputs(
  symbols: string[],
  readmePath: string,
  kdlPath: string,
  csvPath: string,
): Promise<void> {
  const [readmeText, kdlText, csvText] = await Promise.all([
    Deno.readTextFile(readmePath),
    Deno.readTextFile(kdlPath),
    Deno.readTextFile(csvPath),
  ]);

  assertSameSymbols("readme.md", symbols, symbolsFromReadme(readmeText));
  assertSameSymbols("tickers.kdl", symbols, symbolsFromKdl(kdlText));
  assertSameSymbols("tickers.csv", symbols, symbolsFromCsv(csvText));

  for (const [name, text] of [
    ["readme.md", readmeText],
    ["tickers.kdl", kdlText],
    ["tickers.csv", csvText],
  ] as const) {
    if (text.includes("\r")) {
      throw new Error(`${name}: contains CR characters; expected LF-only`);
    }
  }
}

if (import.meta.main) {
  const key = envFirst("APCA_API_KEY_ID", "ALPACA_API_KEY_ID", "ALPACA_API_KEY");
  const secret = envFirst(
    "APCA_API_SECRET_KEY",
    "ALPACA_API_SECRET_KEY",
    "ALPACA_SECRET_KEY",
  );
  const base = (
    envFirst(
      "ALPACA_API_URL",
      "ALPACA_API_BASE_URL",
      "APCA_API_BASE_URL",
      "ALPACA_BASE_URL",
    ) ?? "https://api.alpaca.markets"
  ).replace(/\/$/, "");

  const logPath = join(scriptDir, "alpaca_tickers_fetch.log");

  if (!key || !secret) {
    console.error(
      "Missing Alpaca credentials: set APCA_API_KEY_ID + APCA_API_SECRET_KEY, " +
        "or ALPACA_API_KEY_ID + ALPACA_API_SECRET_KEY, " +
        "or ALPACA_API_KEY + ALPACA_SECRET_KEY.",
    );
    Deno.exit(1);
  }

  const params = new URLSearchParams({
    status: "active",
    asset_class: "us_equity",
  });
  const url = `${base}/v2/assets?${params}`;

  let raw: string;
  try {
    const resp = await fetch(url, {
      headers: {
        "APCA-API-KEY-ID": key,
        "APCA-API-SECRET-KEY": secret,
        Accept: "application/json",
      },
      signal: AbortSignal.timeout(120_000),
    });
    raw = await resp.text();
    if (!resp.ok) {
      console.error(`HTTP ${resp.status}: ${raw}`);
      await logFail(logPath, base, "http", `status=${resp.status} body=${raw.slice(0, 400)}`);
      Deno.exit(1);
    }
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    console.error(`Request failed: ${detail}`);
    const kind = err instanceof TypeError ? "url" : "os";
    await logFail(logPath, base, kind, detail);
    Deno.exit(1);
  }

  let assets: unknown;
  try {
    assets = JSON.parse(raw);
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    console.error(`Invalid JSON from API: ${detail}`);
    await logFail(logPath, base, "json_decode", detail);
    Deno.exit(1);
  }

  if (!Array.isArray(assets)) {
    console.error("Expected a JSON array of asset objects.");
    await logFail(
      logPath,
      base,
      "json_shape",
      `got ${assets === null ? "null" : typeof assets}`,
    );
    Deno.exit(1);
  }

  const tradableOnly = !Deno.args.includes("--all-active");
  const symbolSet = new Set<string>();
  for (const a of assets) {
    if (typeof a !== "object" || a === null) continue;
    const sym = a.symbol;
    if (typeof sym !== "string" || !sym) continue;
    if (tradableOnly && a.tradable !== true) continue;
    symbolSet.add(sym);
  }
  const sortedSymbols = [...symbolSet].sort((a, b) => a.localeCompare(b, "en"));

  const readmePath = join(scriptDir, "readme.md");
  const kdlPath = join(scriptDir, "tickers.kdl");
  const csvPath = join(scriptDir, "tickers.csv");

  const readmeOut = writeReadme(sortedSymbols);
  const kdlOut = writeKdl(sortedSymbols);
  const csvOut = writeCsv(sortedSymbols);

  await writeFileAtomic(readmePath, readmeOut);
  await writeFileAtomic(kdlPath, kdlOut);
  await writeFileAtomic(csvPath, csvOut);

  try {
    await verifyOutputs(sortedSymbols, readmePath, kdlPath, csvPath);
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    console.error(`Output verification failed: ${detail}`);
    await logFail(logPath, base, "verify", detail);
    Deno.exit(1);
  }

  const ts = new Date().toISOString();
  const filt = tradableOnly ? "tradable" : "all_active";
  const outs = "readme.md,tickers.kdl,tickers.csv";
  await appendFetchLog(
    logPath,
    `${ts}\tOK\tsymbols=${sortedSymbols.length}\tout=${outs}\tapi=${base}\tfilter=${filt}\tgen=${GENERATOR}\n`,
  );

  console.log(`Wrote ${sortedSymbols.length} symbols (from Alpaca) to:`);
  console.log(`  ${readmePath}`);
  console.log(`  ${kdlPath}`);
  console.log(`  ${csvPath}`);
  console.log("Verified readme.md, tickers.kdl, and tickers.csv match.");
  console.log(`Logged update at ${ts} (UTC) -> ${logPath}`);
}
